routes/web.php
<?php
use App\Events\SendGlobalNotification;

Route::get('send-notif/{name}', function ($name) {
    event(new SendGlobalNotification($name));
    return "Event has been sent!";
});

Route::get('/testpusher', function () {
    return view('testpusher');
});


Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::get('/spt', 'SptController@index')->name('spt');
Route::get('/sjp', 'SptController@index')->name('sjp');


Route::get('/cetaksinglebarcode/{id}', 'BmnController@CetakRekapBRCD')->name('barcode.id'); //cetakbarcode single

Route::resource('/surattugas','SurattugasController');
Route::resource('/suratdetail','DetailsuratController');
Route::post('/berinomor','SurattugasController@berinomor');

//kompetensiumum
Route::resource('/kompetensiumum','Controllerkompetensiumum');
//kompetensikinerja

Route::resource('/kompetensikinerja','Controllerkompetensikinerja');

//penilaian
Route::get('/showpenilaian','Controllerpenialaiankinerja@showpenilaian')->name('showpenilaian');
Route::resource('/penilaiankerja','Controllerpenialaiankinerja');

//laporan
Route::get('/laporan','LaporankinerjaController@index')->name('laporankinerja');
Route::get('/cetak','LaporankinerjaController@cetak')->name('cetaklaporan');

//test cetak page-break
Route::resource('/testpage','testpageController');


// testcalender
Route::get('/fullcalender','EvenController@index');
// ajax calender
Route::post('/fullcalenderAjax','EvenController@ajax');

Route::resource('/sjp','SjpController');
Route::resource('/spt','SptController');
Route::resource('/bmn','BmnController');
Route::resource('/pegawai','PegawaiController');
Route::resource('/penyedia','PenyediaController');

Route::get('/jsonpegawi/{id}','SurattugasController@jsonpegawai');
Route::get('/cetakpdf/{id}','SurattugasController@cetakpdf');

Route::post('/suratdetail/post','DetailsuratController@tambahpertugas');
Route::delete('/suratdetail/{id}/{surat_id}','DetailsuratController@hapusPegawaiDL');
Route::get('/suratdetail/{id}/{pegawai_id}','DetailsuratController@ubahpegawaiJson');

app/Http/Controllers/PenyediaController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class PenyediaController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('layouts.penyedia.index'); 
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/layouts/penyedia/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <div class="panel panel-warning">
                <div class="panel-heading"><a href="{{route('pegawai.create')}}"><span class="btn btn-sm btn-success">+ Buat Baru</span></a></div>

                <div class="panel-body">
                    <p>DATA PENYEDIA RS / LAB dll</p>
                  

                    <table class="table table-sm">
  <thead>
    <tr>
      <th scope="col">No</th>
      <th scope="col">Nama</th>
      <th scope="col">NIP</th>
      <th scope="col">Tempat/ Tgl Lahir</th>
      <th scope="col">Golongan</th>
      <th scope="col">Jabatan</th>
      <th scope="col">Divisi</th>
      <th scope="col">No Hp</th>
      <th scope="col">Email</th>

    </tr>
  </thead>
  <tbody>
   
  
    <tr>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
    </tr>
  
    
  </tbody>
</table>



                </div>
            </div>
        </div>
    </div>
</div>
@endsection