routes/web.php
<?php
use App\Events\SendGlobalNotification;

Route::get('send-notif/{name}', function ($name) {
    event(new SendGlobalNotification($name));
    return "Event has been sent!";
});

Route::get('/testpusher', function () {
    return view('testpusher');
});


Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::get('/spt', 'SptController@index')->name('spt');
Route::get('/sjp', 'SptController@index')->name('sjp');


Route::get('/cetaksinglebarcode/{id}', 'BmnController@CetakRekapBRCD')->name('barcode.id'); //cetakbarcode single

Route::resource('/surattugas','SurattugasController');
Route::resource('/suratdetail','DetailsuratController');
Route::post('/berinomor','SurattugasController@berinomor');

//kompetensiumum
Route::resource('/kompetensiumum','Controllerkompetensiumum');
//kompetensikinerja

Route::resource('/kompetensikinerja','Controllerkompetensikinerja');

//penilaian
Route::get('/showpenilaian','Controllerpenialaiankinerja@showpenilaian')->name('showpenilaian');
Route::resource('/penilaiankerja','Controllerpenialaiankinerja');

//laporan
Route::get('/laporan','LaporankinerjaController@index')->name('laporankinerja');
Route::get('/cetak','LaporankinerjaController@cetak')->name('cetaklaporan');

//test cetak page-break
Route::resource('/testpage','testpageController');


// testcalender
Route::get('/fullcalender','EvenController@index');
// ajax calender
Route::post('/fullcalenderAjax','EvenController@ajax');

Route::resource('/sjp','SjpController');
Route::resource('/spt','SptController');
Route::resource('/bmn','BmnController');
Route::resource('/pegawai','PegawaiController');
Route::resource('/penyedia','PenyediaController');

Route::get('/jsonpegawi/{id}','SurattugasController@jsonpegawai');
Route::get('/cetakpdf/{id}','SurattugasController@cetakpdf');

Route::post('/suratdetail/post','DetailsuratController@tambahpertugas');
Route::delete('/suratdetail/{id}/{surat_id}','DetailsuratController@hapusPegawaiDL');
Route::get('/suratdetail/{id}/{pegawai_id}','DetailsuratController@ubahpegawaiJson');

app/BarangbmnModel.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class BarangbmnModel extends Model
{
    protected $table = 'barangbmn';


    public function merk(){
        return $this->hasOne('App\MerkModel','id','merk_id');
    }

    public function ruang(){
        return $this->hasOne('App\RuangModel','id','ruang_id');
    }

    public function jenis(){
        return $this->hasOne('App\JenisbrgModel','id','jenis_id');
    }
    
}

app/Detailnilai.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Detailnilai extends Model
{
    protected $table = 'detail_nilai';
    protected $fillable = ['header_nilai_id','kompetensi_umum_id','nilai'];
    public $timestamps = false;
}

app/Detailnilaidua.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Detailnilaidua extends Model
{
    protected $table = 'detail_nilai_dua';
    protected $fillable = ['header_nilai_id','kompetensi_kinerja_id','nilai'];
    public $timestamps = false;
}

app/Detailsurattugas.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Detailsurattugas extends Model
{
    //
    protected $table = 'detailsurattugas';
    protected $fillable = ['surattugas_id','pegawai_id'];
    public $timestamps = false;

    public function pegawai(){
        return $this->hasOne('App\PegawaiModel','id','pegawai_id');
    }

}

app/DevisiModel.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class DevisiModel extends Model
{
    protected $table = 'divisi';

    public function getku(){
        return $this->hasMany('App\ModelKompetensikerja','divisi_id','id');
    }
}

app/EvenModel.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class EvenModel extends Model
{
    protected $table = 'event';
    protected $fillable = ['start', 'end', 'keterangan'];
    public $timestamps = false;
}

app/GolonganModel.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class GolonganModel extends Model
{
    protected $table = 'golongan';
}

app/Headernilai.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Headernilai extends Model
{
    protected $table = 'header_nilai';
    protected $fillable = ['login_id', 'tgl_penilaian','status','pegawai_dinilai'];
    public $timestamps = false;

    public function getuser(){
        return $this->hasMany('App\User','id','pegawai_dinilai');
    }

    public function detail_nilai(){//tabel detai ke-1
        return $this->hasMany('App\Detailnilai','header_nilai_id','id');
    }
}

app/JabatanModel.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class JabatanModel extends Model
{
    protected $table = 'jabatan';
}

app/JenisbrgModel.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class JenisbrgModel extends Model
{
    protected $table = 'jenisbarang';
}

app/MerkModel.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class MerkModel extends Model
{
    protected $table = 'merek';
}

app/ModelDetailnilai.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class ModelDetailnilai extends Model
{
    //
}

app/ModelHeadernilai.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class ModelHeadernilai extends Model
{
    //
}

app/Modelnilairate.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Modelnilairate extends Model
{
    //
}

app/Modelrate.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Modelrate extends Model
{
    protected $table = 'rate';
    protected $fillable = ['nama', 'nilai','status'];
    public $timestamps = false;
}

app/PegawaiModel.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class PegawaiModel extends Model
{
    //
    protected $table = 'pegawai';
    protected $fillable = [];
    public $timestamps = false;

    //divisi
    public function devisi(){
        return $this->hasOne('App\DevisiModel','id','divisi_id');
    }

    //golongan
    public function golongan(){
        return $this->hasOne('App\GolonganModel','id','golongan_id');
    } 

    //jabatan 
    public function jabatan(){
        return $this->hasOne('App\JabatanModel','id','jabatan_id');
    }



}

app/RuangModel.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class RuangModel extends Model
{
    protected $table = 'ruang';
}

app/SatuanModel.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class SatuanModel extends Model
{
    protected $tbale = 'satuan';
    
}

app/SurattugasModel.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class SurattugasModel extends Model
{
    protected $table = 'surattugas';
                // 'konten' =>,
    protected $fillable = ['nomorsurat','aliassurat','acara','tanggal_mulai','tanggal_selesai','koordinator_id','konten','status','status_lampiran','sign_id'];

    public function koordinator(){
        return $this->hasOne('App\PegawaiModel','id','koordinator_id');
        
    }

    public function detailsurat(){
        return $this->hasMany('App\Detailsurattugas','surattugas_id','id');
    }
}

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'nama', 'email', 'password','username'
    ];
    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    public function getdivisi(){
        return $this->hasOne('App\DevisiModel','id','divisi_id');
    }
}

resources/views/home.blade.php
@extends('layouts.app')
@section('content')
<div class="container">
    {{-- profil --}}
    {{-- <div class="row" style="margin:0px !important;padding:0px !important">
        <div class="col-md-12" style="margin:0px !important;padding:0px !important">
            
        </div>
    </div> --}}
    {{-- end profil --}}

    <div class="row" style="">
        <div class="col-md-8">
            <div class="panel panel-default" >
                <div class="panel-heading" style="background-color:#305399;color:white">Pegawai yang sudah dinilai :</div>
                <div class="panel-body">
                    @if (session('status'))
                        <div class="alert alert-success">
                            {{ session('status') }}
                        </div>
                    @endif
                    {{-- table yang sudah diisi --}}
                    <table id="example" class="table table-striped table-bordered" style="width:100%">
                        <thead>
                            <tr>
                                <th>NO</th>
                                <th>NAMA PEGAWAI</th>
                                <th>DIVISI</th>
                                <th>TANGGAL</th>
                                <th></th>   
                            </tr>
                        </thead>
                            <tbody>
                            <?php $i=1?>
                            @foreach($data as $key => $value)
                            <tr>
                                <td>{{ $i++ }}</td>
                                <td>{{ $value->getuser[0]->nama}}</td>
                                <td>{{ $value->getuser[0]->getdivisi->namadivisi }}</td>
                                <td>{{ $value->tgl_penilaian }}</td>
                                <td><button class="btn btn-xs btn-warning">hapus</button></td>
                                
                            </tr>      
                            @endforeach
                            

                            </tbody>
                        </table>

                    {{-- end table sudah diisi penilaian --}}

                    {{-- progressbar --}}
                    <label>yang sudah dinilai : </label>
                    <div class="progress">
                        <div class="progress-bar" role="progressbar" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100" style="min-width: 2em;">
                            0%
                        </div>
                    </div>

                    {{-- end progressbar --}}


                    
                </div>
            </div>
        </div>

        <div class="col-md-4">
            <div class="panel panel-default">
                <div class="panel-heading" style="background-color:#305399;color:white">Pemberitahuan</div>

                <div class="panel-body">
                    @if (session('status'))
                        <div class="alert alert-success">
                            {{ session('status') }}
                        </div>
                    @endif

                    {{-- PLH --}}
                    <div class="row">
                        <div class="col-md-12">
                            PLH Hari ini : <br>
                        </div>
                        
                    </div>

                    {{-- sisacuti --}}
                    <div class="row">
                        <div class="col-md-12">
                            Sisa Cuti Anda :
                        </div>
                        
                    </div>
                    {{-- pengajuan cuti --}}
                    <div class="row">
                        <div class="col-md-12">
                            <a href="#" class="btn btn-sm btn-default" style="float:right;background-color:#305399;color:white">Pengajuan Cuti <span class="glyphicon glyphicon-circle-arrow-right"></span></a>
                        </div>
                    </div>

                    
                </div>
            </div>
        </div>


    </div>


    {{-- pengumuman footer --}}
    <div class="row">
        <div class="col-md-12">
                <div class="panel panel-default" >
                    <div class="panel-heading" style="background-color:#305399;color:white">Info tambahan :</div>
                        <div class="panel-body">
                        Belum ada info terbaru 
                        </div>
                </div>
                
        </div>
    </div>

</div>
@endsection
@section('js')
    <script>
        $(document).ready(function() {
            //$('#example').DataTable();

            $('#example').DataTable( {
                responsive: true,
                "lengthMenu": [[5, 25, 50, -1], [5, 25, 50, "All"]]
            } );
        } );
    </script>
@endsection

resources/views/layouts/kompetensiumum/create.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <div class="panel panel-warning">
                <div class="panel-heading"><a href="{{route('kompetensiumum.create')}}"><span class="btn btn-sm btn-success">+ Buat Baru</span></a></div>

                <div class="panel-body">
                    <p>Data Kompetensi Umum</p>
                    <!-- info -->
                    @if(isset($info))
                    <div class="alert alert-success" role="alert">{{$info}}</div>
                    @else
                    
                    @endif

                    
                    <form method="POST" action="{{route('kompetensiumum.store')}}">
                      {{csrf_field()}}
                      <div class="form-group">
                        <label for="exampleInputEmail1">Nama</label>
                        <input type="text" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="masukkan nama kompetensi" autocomplete="off" name="nama" required >
                        
                        
                      </div>
                      <div class="form-group">
                        <label for="exampleInputPassword1">Keterangan</label>
                        <input type="text" class="form-control" id="" placeholder="masukkan keterangan" name="keterangan" required autocomplete="off">
                       
                      </div>
                      <button type="submit" class="btn btn-primary">Simpan</button>
                    </form>
                  
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/layouts/kompetensiumum/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <div class="panel panel-warning">
                <div class="panel-heading"><a href="{{route('kompetensiumum.create')}}"><span class="btn btn-sm btn-success">+ Buat Baru</span></a></div>

                <div class="panel-body">
                    <p>Data Kompetensi Umum</p>
                  

                    <table class="table table-sm">
                      <thead>
                        <tr>
                          <th scope="col">No</th>
                          <th scope="col">Nama</th>
                          
                          <th scope="col">Keterangan</th>
                          <th scope="col"></th>
                        </tr>
                      </thead>
                      <tbody>
                        <?php
                          $i =1;
                        ?>
                       <!-- data -->
                       @foreach($data as $dt)
                       <tr>
                          <td>{{$i++}}</td>
                          <td>{{$dt->nama}}</td>
                          <td>{{$dt->keterangan}}</td>
                          <td><a href="#" class="btn btn-default btn-sm">Ubah</a></td>
                        </tr>

                       @endforeach
                      </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/layouts/kompetensiumum/show.blade.php
show.blade.php

resources/views/layouts/penilaian/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
{{-- modal --}}
<div class="row">
	<div class="col-md-12">
		{{-- isimodal --}}
		<div id="myModal" class="modal fade" role="dialog">
			<div class="modal-dialog">

				<!-- Modal content-->
				<div class="modal-content">
				<div class="modal-header" style="background-color:#305399;color:white">
					<button type="button" class="close" data-dismiss="modal">&times;</button>
					<h4 class="modal-title">Data Pegawai yang sudah dinilai</h4>
				</div>
				<div class="modal-body">
					{{-- tabel --}}
					<table id="example" class="table table-striped table-bordered" style="width:100%">
                        <thead>
                            <tr>
                                <th>NO</th>
                                <th>NAMA PEGAWAI</th>
                                <th>DIVISI</th>
                                <th>TANGGAL</th>
                                   
                            </tr>
                        </thead>
                            <tbody>
                            <?php $i=1?>
                            @foreach($datainput as $key => $value)
                            <tr>
                                <td>{{ $i++ }}</td>
                                <td>{{ $value->getuser[0]->nama}}</td>
                                <td>{{ $value->getuser[0]->getdivisi->namadivisi }}</td>
                                <td>{{ $value->tgl_penilaian }}</td>
                               
                                
                            </tr>      
                            @endforeach
                            

                            </tbody>
                        </table>
					{{-- end tabel --}}
				</div>
				<div class="modal-footer">
					<button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
				</div>
				</div>

  </div>
</div>

	</div>
</div>
{{-- end modal --}}
	<div class="row" >
		<div class="col-md-12">
			 <div class="panel panel-default">
			 	<div class="panel-heading" style="background-color:#305399;color:white">Kriteria Nilai</div>

			 	<div class="panel-body">
			 		<span class="label label-primary">Sangat Baik - 100 POIN</span>
			 		<span class="label label-success">Baik - 90 POIN</span>
			 		<span class="label label-info">Cukup - 80 POIN</span>
			 		<span class="label label-warning">Tidak Baik - 70 POIN</span>
			 		<span class="label label-danger">Sangat Tidak Baik - 60 POIN</span>
			 	</div>
			 </div>
			
		</div>
	</div>

	<!-- pengisian / form -->
	<div class="row">
		<div class="col-md-12">
			 <div class="panel panel-default">
			 	<div class="panel-heading" style="background-color:#305399;color:white">Form Pemberian Nilai / Rate <button type="button" class="btn btn-default btn-xs" style="color:white;background-color:#305399;float:right" data-toggle="modal" data-target="#myModal">Lihat</button></div>
			 	<div class="panel-body">
			 		<!-- row body-->

			 		<div class="row">
			 			<div class="col-md-8">
			 					<form method="GET" action="{{url('/showpenilaian')}}">
			 						<label>	** Pegawai yang dinilai kinerjanya : </label>
			 						<select class="js-example-basic-single" name="pegawai" style="font-size: 12px">
									 		<option value="-">-</option>
			 							@foreach($pegawai as $pg)
	                                  		<option value="{{ Illuminate\Support\Facades\Crypt::encryptString($pg->id)}}">{{ title_case($pg->nama) }}</option>
	                                  	@endforeach
	                                 
	                                </select>
	                                <button class="btn btn-sm btn-success">cari</button>
			 					</form>
								
			 			</div>

						 <div class="col-md-4">
						 
								@if (session('status'))
									<div class="alert alert-warning">
										{{ session('status') }}
									</div>
								@endif

								@if (session('notif'))
									<div class="alert alert-warning">
										{{ session('notif') }}
									</div>
								@endif

								@if (session('msg'))
									<div class="alert alert-success">
										{{ session('msg') }}
									</div>
								@endif

								@if(isset($getPegawai))
									<div class="alert alert-info" style="padding:2px;float:left;margin-top:5px"><span class="glyphicon glyphicon-user"></span>
										<b>{{ $getPegawai->nama }}</b>
									</div>
								@else
								@endif
									
									
			 			</div>
						 
			 		</div>

			 		<!-- kompetensi umum -->
			 		<div class="row">
			 			<form method="POST" action="{{route('penilaiankerja.store')}}">
			 			<div class="col-md-12">
			 					<!-- tabel k.umum -->

			 					@if(isset($getPegawai))
			 						<input type="hidden" name="pegawai_yang_dinilai" value="{{$getPegawai->id}}">
			 					@else
			 						
			 					@endif
			 					{{csrf_field()}}
			 					
			 					<span class="label label-default">Kompetensi Umum</span>
			 					<table  class="table table-striped">
			 							<thead>
			 								<tr style="">
			 									<th width="50px" style="">No</th>
			 									<th width="650px" style="">Butir Penilaian</th>
			 									<th style="">Pemberian Nilai / Rate</th>
			 								</tr>
			 							</thead>
			 							<tbody style="">
			 								<?php
			 								$a=1;
			 								?>
			 								@if(isset($datamu))
			 								@foreach($datamu as $du)
			 								<tr>
			 									<td style="border: none !important;">{{$a++}}</td>
			 									<td style="border: none !important;">{{$du->nama}}<input type="hidden" value="{{$du->id}}" name="inKU[]" /></td>
			 									<td style="border: none !important;">
			 										<?php
			 										$countr = 1;
			 										?>
			 										<select name="ratemu[]">
			 											@foreach($rate as $rt)
			 											<option value="{{$rt->nilai}}">{{$rt->nama}}</option>
			 											@endforeach
			 											
			 										</select>
			 										
			 										
			 									</td>
			 									
			 								</tr>
			 								@endforeach
			 								@else
			 								<tr>
			 									<td></td>
			 									<td></td>
			 									<td></td>
			 								</tr>


			 								@endif
			 							</tbody>
			 					</table>
			 					<!-- end tabel k.umum -->
			 			</div>
			 		</div>

			 		<!-- kompetensi kinerja -->
			 		<div class="row">
			 			<div class="col-md-12">

			 				<!-- tabel kompetensi kinerja -->
			 				<span class="label label-default">Kompetensi Kinerja</span>
			 					<table  class="table table-striped">
			 							<thead>
			 								<tr>
			 									<th width="50px">No</th>
			 									<th width="650px">Butir Penilaian</th>
			 									<th>Pemberian Nilai / Rate</th>
			 									

			 								</tr>
			 							</thead>
			 							<tbody>
			 								<?php 
			 								$i=1;
			 								?>
			 								@if(isset($butirMK))
			 								@foreach($butirMK as $butir)
			 								<tr>
			 									<td style="border: none !important;">{{$i++}}</td>
			 									<td style="border: none !important;">{{$butir->nama}}<input type="hidden" value="{{$butir->id}}" name="inKK[]" /></td>
			 									<td style="border: none !important;">
			 										<select name="ratemk[]">
			 											@foreach($rate as $rt)
			 											<option value="{{$rt->nilai}}">{{$rt->nama}}</option>
			 											@endforeach
			 										</select>
			 									</td>
			 									
			 								</tr>
			 								@endforeach
			 								@else
			 								<tr>
			 									<td></td>
			 									<td></td>
			 									<td></td>
			 								</tr>

			 								@endif
			 							</tbody>
			 					</table>
			 					<!-- end tabel k.umum -->
			 				<!-- end tabel kompetensi kinerja-->
			 			
			 			</div>
			 		</div>

			 		<div class="row">
			 			<div class="col-md-12" >
						 @if(isset($btnsimpan))
						  {!! $btnsimpan !!}
						 @else
						 @endif
						
			 				

			 			</div>
			 		</div>
			 		</form>

			 		<!-- end row body -->

			 	</div>
			 </div>


			
		</div>
	</div>

	<!-- end pengisian -->
</div>
@endsection
@section('js')
<script type="text/javascript">
	  	$(document).ready(function() {
    		$('.js-example-basic-single').select2();
			$('#example').DataTable( {
                responsive: true,
                "lengthMenu": [[5, 25, 50, -1], [5, 25, 50, "All"]]
            } );
		});



  </script>
@endsection

resources/views/testpusher.blade.php
<!DOCTYPE html>
<head>
  <title>Pusher Test</title>
  <script src="https://js.pusher.com/7.0/pusher.min.js"></script>
  <script>

    // Enable pusher logging - don't include this in production
    Pusher.logToConsole = true;

    var pusher = new Pusher('8d435c998b731ad512b7', {
      cluster: 'ap1'
    });

    var channel = pusher.subscribe('global-notif');
    channel.bind('my-event', function(data) {
        console.log(data)
      alert(JSON.stringify(data));
    });
  </script>
</head>
<body>
  <h1>Pusher Test</h1>
  <p>
    Try publishing an event to channel <code>my-channel</code>
    with event name <code>my-event</code>.
  </p>
</body>