routes/web.php
<?php
use App\Events\SendGlobalNotification;

Route::get('send-notif/{name}', function ($name) {
    event(new SendGlobalNotification($name));
    return "Event has been sent!";
});

Route::get('/testpusher', function () {
    return view('testpusher');
});


Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::get('/spt', 'SptController@index')->name('spt');
Route::get('/sjp', 'SptController@index')->name('sjp');


Route::get('/cetaksinglebarcode/{id}', 'BmnController@CetakRekapBRCD')->name('barcode.id'); //cetakbarcode single

Route::resource('/surattugas','SurattugasController');
Route::resource('/suratdetail','DetailsuratController');
Route::post('/berinomor','SurattugasController@berinomor');

//kompetensiumum
Route::resource('/kompetensiumum','Controllerkompetensiumum');
//kompetensikinerja

Route::resource('/kompetensikinerja','Controllerkompetensikinerja');

//penilaian
Route::get('/showpenilaian','Controllerpenialaiankinerja@showpenilaian')->name('showpenilaian');
Route::resource('/penilaiankerja','Controllerpenialaiankinerja');

//laporan
Route::get('/laporan','LaporankinerjaController@index')->name('laporankinerja');
Route::get('/cetak','LaporankinerjaController@cetak')->name('cetaklaporan');

//test cetak page-break
Route::resource('/testpage','testpageController');


// testcalender
Route::get('/fullcalender','EvenController@index');
// ajax calender
Route::post('/fullcalenderAjax','EvenController@ajax');

Route::resource('/sjp','SjpController');
Route::resource('/spt','SptController');
Route::resource('/bmn','BmnController');
Route::resource('/pegawai','PegawaiController');
Route::resource('/penyedia','PenyediaController');

Route::get('/jsonpegawi/{id}','SurattugasController@jsonpegawai');
Route::get('/cetakpdf/{id}','SurattugasController@cetakpdf');

Route::post('/suratdetail/post','DetailsuratController@tambahpertugas');
Route::delete('/suratdetail/{id}/{surat_id}','DetailsuratController@hapusPegawaiDL');
Route::get('/suratdetail/{id}/{pegawai_id}','DetailsuratController@ubahpegawaiJson');

app/Http/Controllers/SurattugasController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\PegawaiModel as pm;
use App\SurattugasModel as sm;
use App\Detailsurattugas as dst;
use PDF;
use SimpleSoftwareIO\QrCode\Facades\QrCode;
use Carbon\Carbon;
use DB;
use Illuminate\Support\Facades\Storage;
// use App\Http\Controllers\Storage;

class SurattugasController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function __construct()
    {
        $this->middleware('auth');
    }
    public function index()
    {
        $datasurat = sm::orderBy('id','DESC')->get();
        return view('layouts.surattugas.index',compact('datasurat'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $pegawais = pm::orderBy('nama','ASC')->get();
        // dd($pegawasis);
        return view('layouts.surattugas.create',compact('pegawais'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {

        /*jika pegawai lebih dari 8 orang maka masuk ke cetak lampiran */ 
        $nomorconc = $request->pertama.'.'.$request->kedua.'.'.$request->ketiga.'/'.$request->keempat;
        // dd($nomorconc);

        // dd($request->all());
        // dd($request->petugas);
        // $dataarry = count($request->petugas);
        // dd($dataarry);
        if(empty($request->petugas)){
            dd("Petugas masih kosong tolong diisi");
        }else{
            // jika sukses 

            //pengecekkan jika petugas lebih dari 8 maka dibuatkan lampiran 
            $datasurat = sm::create([
                'nomorsurat' =>$request->nomer,
                'aliassurat' =>$nomorconc,
                'acara' =>$request->perihal,
                'tanggal_mulai' =>Carbon::createFromFormat('d/m/Y', $request->tglmulai)->format('Y-m-d'),
                'tanggal_selesai' =>Carbon::createFromFormat('d/m/Y', $request->tglselesai)->format('Y-m-d'),
                'koordinator_id'=>$request->koordinator,
                'konten' =>$request->editor1,
                'status_lampiran' =>0,
                'sign_id'=>$request->persetujuan,
                'created_at' => Carbon::now()
            ]);

            // insert tabel detail
            foreach($request->petugas as $pt){
                $dst = dst::create([
                    'surattugas_id'=> $datasurat->id,
                    'pegawai_id'=> $pt
                ]);

            }
            

            dd($dst);


            dd($datasurat);
        }
      

        


        // preview dulu
        $qr = QrCode::size(50)->generate('subangkit');
        // $qr = 'data';
        // $datasurat = $request->all();

        // $pdf = PDF::loadView('layouts.surattugas.print.preview',['datasurat'=>$datasurat,'qr'=>$qr]);
        // return $pdf->stream(); //browser
        //return $pdf->download('laporan-pegawai.pdf'); // download
        
        
    
        // dd($request->all());
        $datasurat = $request->all();
        
        // dd($datasurat['editor1']);
        return view('layouts.surattugas.print.preview',compact('datasurat','qr'));
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {

    //    nnomor di pecah 
        $surat = sm::find($id);
        // dd($surat);
        // dd($surat->detailsurat);


    //   konten
       $pegawais = pm::orderBy('nama','ASC')->get();
       return view('layouts.surattugas.show',compact('pegawais','surat'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }

    public function jsonpegawai($id){//json pilih
        $pegawai = pm::find($id);
        $data['id'] = $pegawai->id;
        $data['nik'] = $pegawai->nik;
        $data['nama'] = $pegawai->nama;
        $data['pangkat'] = $pegawai->golongan->namapangkat."/".$pegawai->golongan->golongan;
        $data['jabatan'] = $pegawai->jabatan->namajabatan;
        // dd($data);
        return response()->json($data);
    }


    public function cetakpdf($id){
        // dd($id);
        $surat = sm::find($id);
        $qr = QrCode::size(60)->generate('subangkit');
        // $qr=QrCode::size(60)->format('png')->mergeString(Storage::get('public/logo/logo.png'))->generate('subangkit');
        
        // $qr=QrCode::size(60)->format('png')->mergeString())->generate('subangkit');
        // dd($qr);
        //asset('storage/uploads/avatar/default.jpg')
        // dd($surat);
        return view('layouts.surattugas.download.index',compact('surat','qr'));

        // $pdf = PDF::loadView('layouts.surattugas.download.index',['surat'=>$surat,'qr'=>$qr]);
        // $pdf = $pdf->setPaper('legal');
        // return $pdf->stream(); //browser
        // return $pdf->download('laporan-pegawai.pdf'); // download
        // dd($surat);
    }

    public function berinomor(Request $request){
        // $wordCount = Wordlist::where('id', '<=', $correctedComparisons)->count();
        $cek = sm::where('nomorsurat','=',$request->nomor)->count();
        if($cek == 1){
            // dta ada
            $data = array(
                'status_code' => 1
            );
        }else{
            // update nomer surat yang ada di tabel surattugas 
            $surat = sm::find($request->idsurat);
            $surat->nomorsurat = $request->nomor;
            $surat->save();
            $data = array(
                'status_code' => 0
            );
        }
        return response()->json($data);

    }


}

resources/views/layouts/surattugas/create.blade.php
@extends('layouts.app') @section('content') <div class="container">
@push('css')
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.7/css/bootstrap.min.css">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.7.14/css/bootstrap-datetimepicker.min.css">
<!-- script untuk css -->
<style type="text/css">
  .select2 {
  width:100%!important;
  }


</style>
@endpush
<form action="{{route('surattugas.store')}}" method="POST">
  <div class="row">
    <div class="col-md-12">
      <div class="panel panel-default">
        <div class="panel-heading">FORM SURAT TUGAS</div>
        <div class="panel-body">
            <!-- form -->
            <div class="row">
              
                {{csrf_field()}}
                <div class="col-md-4">
                  <!-- konten kiri -->
                  

                  
                    <label for="email">NOMOR:</label><br>
                    <select name="pertama" id="">
                    <option value="yk">YK</option>
                    <option value="ku">KU</option>
                    <option value="ym">YM</option>
                  </select>

                  <select name="kedua" id="">
                    <option value="01">01</option>
                    <option value="02">02</option>
                    <option value="03">03</option>
                  </select>

                  <select name="ketiga" id="">
                    <option value="01">01</option>
                    <option value="02">02</option>
                    <option value="03">03</option>
                  </select>
                  /
                  <select name="keempat" id="">
                    <option value="XLIX.1">XLIX.1</option>
                    <option value="XLIX.2">XLIX.2</option>
                    <option value="XLIX.3">XLIX.3</option>
                  </select>
                  / 
                  <input type="number" name="nomer" placeholder="ex:3333" style="width:100px;background-color:#00b894;border:1px solid;color:white;border-radius:5px"/>
                  <br><span style="color:#2d3436;font-size:8pt">note : silahkan dikosongi jika belum tahu nomernya</span>
                  
                  <div class="form-group">
                    <label for="email">ACARA /PERIHAL:</label>
                    <input type="text" class="form-control" id="email" name="perihal">
                  </div>
                  <label for="">KOORDINATOR <input type="checkbox" id="koor" name="koor" value="koor"></label>
                  <select class="form-control form-control-sm" id="koordinator" name="koordinator">
                        <option value="0">-pilih-</option>
                        @foreach($pegawais as $p)
                        <option value="{{$p->id}}" >{{$p->nama}}</option>
                        @endforeach
                  </select>

                  <div class="form-group">
                    <label for="email">TANGGAL MULAI DL:</label>
                      <div class='input-group date' id='datetimepicker1'>
                      <input type='text' class="form-control" name="tglmulai" />
                      <span class="input-group-addon">
                          <span class="glyphicon glyphicon-calendar"></span>
                      </span>
                      </div>
                  </div>

                  <div class="form-group">
                    <label for="email">TANGGAL SELESAI:</label>
                    <div class='input-group date' id='datetimepicker2'>
                      <input type='text' class="form-control" name="tglselesai"/>
                      <span class="input-group-addon">
                          <span class="glyphicon glyphicon-calendar"></span>
                      </span>
                      </div>
                  </div>

                  <!-- end kiri -->
                </div>

                <div class="col-md-8">
                    <!-- Petugas / Pegawai -->
                    <div class="row">
                      <div class="col-md-4">
                      <label for="exampleFormControlTextarea1">PEGAWAI</label>
                      <select class="form-control form-control-sm" id="pegawai">
                        <option value="-">-pilih-</option>
                        @foreach($pegawais as $p)
                        <option value="{{$p->id}}" >{{$p->nama}}</option>
                        @endforeach
                      </select>

                      </div>
                      <div class="col-md-2">
                      <label for="exampleFormControlTextarea1" style="color:white">.</label>
                        <button class="form-control btn btn-sm btn-success" id="pilih" style="background-color:#00b894;border-color:#00b894">Pilih</button>
                      </div>

                      <div class="col-md-2">
                      <label for="exampleFormControlTextarea1" style="color:white">.</label>
                      <button class="form-control btn btn-sm btn-default" id="bersih">bersihkan</button>
                       
                      </div>
                    </div>
                    <br>

                    <!-- end pegawai -->
                    
                   <!-- konten kanan -->

                   <!-- tabel pegawai detail  -->
                   <div class="row">
                     <div class="col-md-12">
                      <table width="100%">
                        <thead style="background-color:#00b894;color:white;margin-top:10px;margin-bottom:10px">
                          <th style="padding: 5px;px">NAMA</th>
                          <th>NIP/NIK</th>
                          <th>PANGKAT/GOL</th>
                          <th>JABATAN</th>
                        </thead>
                        <tbody id="detail">
                          
                          
                        </tbody>
                        
                      </table>
                     </div>

                   </div>

                   <!-- end detail tabel pegawai  -->
                   <br>

                   <div class="form-group">
                        <label for="exampleFormControlTextarea1">KONTEN</label>
                        <textarea class="form-control" id="konten" rows="3" name="editor1"></textarea>
                    </div>
                    <div class="form-group">
                        <label for="exampleFormControlTextarea1">KEPALA BALAI / PLH</label>
                        <select name="persetujuan" class="form-control form-control-sm" id="persetujuan">
                          @foreach($pegawais as $ps)
                          <option value="{{$ps->id}}">{{$ps->nama}}</option>
                          @endforeach
                        </select>
                      </div>

                    <!-- radiobutton  -->
                    <div class="row">

                     
                        <!-- <div class="col-md-2">
                        <input type="radio" id="css" name="ckr" value="TU"> TU

                        </div>

                        <div class="col-md-2">
                        <input type="radio" id="css" name="ckr" value="KAK"> KAK

                        </div> -->

                    </div>
                    

                    <!-- end radiobutton  -->
                    

                  

                  
                   <!-- en kanan -->

                </div>

            </div>

            <div class="row">
               
                    <div class="col-md-4">
                      
                    </div>

                    <div class="col-md-4">
                       <!-- <input type="submit" value="kirim"> -->
                        <button type="submit" class="btn btn-md btn-success" style="background-color:#00b894;border-color:#00b894">SIMPAN</button>
                        <button class="btn btn-md btn-warning" style="background-color:#fdcb6e;border-color:#fdcb6e">BERSIHKAN</button>
                    </div>

                    <div class="col-md-4">
                       
                    </div>  
                    
            </div>
            <!-- end form -->
        </div>
      </div>
    </div>
  </div>
  </form>
</div> @endsection

@section('js')
<script src="/vendor/unisharp/laravel-ckeditor/ckeditor.js"></script>

<!-- <script src="/vendor/unisharp/laravel-ckeditor/adapters/jquery.js"></script> -->
<script type="text/javascript">
  
  $(document).ready(function(){

    // check uncheck 

    $("#koor").change(function() {
    if(this.checked) {
      // $('#koordinator').attr('disabled','disabled');
      $("#koordinator").removeAttr('disabled');
        //I am checked
        // alert("checkd")
    }else{
      $('#koordinator').attr('disabled','disabled');
        //I'm not checked
        // alert("not chacked")
    }
  });



    $('#datetimepicker1').datetimepicker({
      format:'DD/MM/YYYY'
    });

    $('#datetimepicker2').datetimepicker({
      format:'DD/MM/YYYY'
    });
    var htmltu;
    var htmlkak;
    var a = templatetu();
    $('#konten').val(a);

    $('#bersih').click(function(e){
      e.preventDefault();
      $('#detail').html("");
    });
    


    // radio buttin untuk ck editor
    $('input:radio[name=ckr]').change(function() {
        if (this.value == 'TU') {
            alert("TU");
            var a = templatetu();
            $('#konten').val('testdata');
            console.log(a);
        }
        else if (this.value == 'KAK') {
            alert("KAK");
        }
    }); 
    // end radio button
    $('#koordinator').attr('disabled','disabled');
    

    // onclick 
    $('#pilih').click(function(e){
      e.preventDefault();
      var pilihan = $('#pegawai').find(":selected").val();
      var test = "/jsonpegawi/"+pilihan;
      // console.log(test);
      $.ajax({
        url: "/jsonpegawi/"+pilihan,
        type: 'GET',
        success(data){
          console.log(data)
          var html;
                         html = '<tr style="border-bottom:solid 1px #00b894">;'
                            
                            html += '<td><input type="hidden" name="petugas[]" value="'+data.id+'">'+data.nama+'</td>;'
                            html += '<td>'+data.nik+'</td>;'
                            html += '<td>'+data.pangkat+'</td>;'
                            html += '<td>'+data.jabatan+'</td>;'
                          html += '</tr>;'
          // append
          $('#detail').append(html);
        }
      });
      
    });
    
    CKEDITOR.replace( 'editor1' );
    
    
    // $('#golongan').select2();

    //  $('#jabatan').select2();
    //  $('#divisi').select2();


    $('#add').click(function(event){
    var tambahkotak = $('.isi');
    var selectBox = document.getElementById("selectBox");
    var selectedValue = selectBox.options[selectBox.selectedIndex].value;

    console.log(selectedValue);
    // alert(selectedValue)

    event.preventDefault(); 
    var tabel ='';
    $('<div><label><input name="pegawai[]" value="'+selectedValue+'"/></label><button id="remove" class="btn btn-sm btn-danger" style="padding-bottom:3px;margin-bottom:3px">X</button></div>').appendTo(tambahkotak);
  });



  //   $('<div id="box"><textarea id="name" class="name"/></textarea><button id="remove">Hapus</button></div>').appendTo(tambahkotak);
  // });
  
  $('body').on('click','#remove',function(){  
    $(this).parent('div').remove(); 
  });   


  });


  function templatetu(){
    // htmltu 
    htmltu = '<p>Untuk melaksanakan kegiatan yang akan dilaksanakan dengan rincian sebagai berikut :</p><p>Acara&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;: Seleksi CASN Kementerian Kesehatan RI Pada Kantor Regional II BKN&nbsp;Surabaya Jawa Timur&nbsp;&nbsp;&nbsp;&nbsp;<br>Hari / Tanggal&nbsp;&nbsp;&nbsp;&nbsp;: Senin - Kamis, 11 - 14 Oktober 2021&nbsp;&nbsp;&nbsp;&nbsp;<br>Tempat&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; : Gedung Jatim Expo&nbsp;<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Jl. Ahmad Yani No. 99 Surabaya&nbsp;&nbsp;</p>'
    return htmltu;
  }

  function templatekak(){
  }


</script>

@endsection

resources/views/layouts/surattugas/index.blade.php
@extends('layouts.app')
@push('css')

<link rel="stylesheet" href="https://cdn.datatables.net/1.11.3/css/jquery.dataTables.min.css">
@endpush
@section('content')
<div class="container">

<!-- modal open -->

  <!-- Trigger the modal with a button -->
  <!-- <button type="button" class="btn btn-info btn-lg" data-toggle="modal" data-target="#myModal">Open Modal</button> -->

  <!-- Modal -->
  <div class="modal fade" id="myModal" role="dialog">
    <div class="modal-dialog">
    
      <!-- Modal content-->
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal">&times;</button>
          <h4 class="modal-title">Form Beri Nomor</h4>
        </div>
        <div class="modal-body">
          <span id="info">
          

          </span>
          <form action="#" method="post" id="formnomor">
            {{csrf_field()}}
            <span id="idsurat"></span>
          
          <div class="input-group">
      <input type="number" class="form-control" placeholder="beri nomor" name="nomor" id="nomor" required>
      <div class="input-group-btn">
        <button class="btn btn-default" type="submit" id="berinommor"><i class="glyphicon glyphicon-floppy-disk"></i> Berinomor</button>
      </div>
    </div>
          </form>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default tutup" data-dismiss="modal" >Close</button>
        </div>
      </div>
      
    </div>
  </div>

<!-- modal close -->



<!-- cetak all barcode fileter -->
<!-- <div class="row">
  <div class="col-md-12">
    <div class="panel panel-info">
      <div class="panel-heading">
        <p>Filter cetak </p>

      </div>

      <div class="panel-body">
        <form action="#">
        <div class="form-group">
          <label for="sel1">Pilih Devisi:</label>
          <select class="form-control" id="sel1">
            <option>All</option>
            <option>TU</option>
          </select>
          <button class="btn btn-md btn-primary" style="margin-top:5px"> CARI </button>
        </div>
          
        </form>

      </div>

    </div>

  </div>

</div> -->
<!-- end cetak barcode -->
    <div class="row">
        <div class="col-md-12">
            <div class="panel panel-warning">
                <div class="panel-heading"><a href="{{route('surattugas.create')}}"><span class="btn btn-sm btn-success">+ Buat Baru</span></a></div>
  
                <div class="panel-body">
                    <p>DATA SURAT KELUAR DL</p>
                    <table id="example" class="table" style="width:100%">
  <thead >
    <tr >
      <th>NOMER SURAT</th>
      <th>ACARA / KEGIATAN </th>
      <th>KOORDINATOR</th>
      <th>PETUGAS </th>
      <th>TANGGAl BERANGKAT</th>
      <th>TANGGAL SELESAI</th>
      
      <th></th>
    </tr>
  </thead>

  
  <tbody>
   
  @foreach($datasurat as $dt)
  @if(empty($dt->nomorsurat))
    <tr style='background-color:#fab1a0;color:white'>
      <td>
        @if(empty($dt->nomorsurat))
          <input type="hidden" name="idsurat" id="idsurat" value="{{$dt->id}}">
          <!-- id="berinomor" -->
          <a href="#" class="btn btn-sm btn-default style=background-color:#b2bec3"  data-toggle="modal" onClick="idSurat({{$dt->id}})">Beri Nomer</a>
        @else
          {{$dt->nomorsurat}}
        @endif
       
      </td>
      <td>{{$dt->acara}}</td>
      <td>{{$dt->koordinator['nama']}}</td>
      <!-- <td></td> -->
      <td>
        <!-- {{$dt->detailsurat}} -->
        @foreach($dt->detailsurat as $pg)
          {{$pg->pegawai['nama']}},<br>
        @endforeach


      </td>
      <td>{{$dt->tanggal_mulai}}</td>
      <td>{{$dt->tanggal_selesai}}</td>
      <td><a href="{{URL::to('/surattugas')}}/{{$dt->id}}" class="btn btn-xs btn-default" target="blank" style="background-color:#fdcb6e;border-color:#fdcb6e">UBAH</a> <a href="{{URL::to('/cetakpdf')}}/{{$dt->id}}" class="btn btn-xs btn-default" target="_blank">PDF</a><a href="" class="btn btn-xs btn-default">HAPUS</a></td>
    </tr>

    @else

    <tr>
      <td>
        @if(empty($dt->nomorsurat))
          <a href="#" class="btn btn-xs btn-default style=background-color:##b2bec3" id="berinomor" data-toggle="modal">Beri Nomer</a>
        @else
          {{$dt->nomorsurat}}
        @endif
       
      </td>
      <td>{{$dt->acara}}</td>
      <td>{{$dt->koordinator['nama']}}</td>
      <!-- <td></td> -->
      <td>
        <!-- {{$dt->detailsurat}} -->
        @foreach($dt->detailsurat as $pg)
          {{$pg->pegawai['nama']}},<br>
        @endforeach


      </td>
      <td>{{$dt->tanggal_mulai}}</td>
      <td>{{$dt->tanggal_selesai}}</td>
      <td><a href="{{URL::to('/surattugas')}}/{{$dt->id}}" class="btn btn-xs btn-default" target="blank" style="background-color:#fdcb6e;border-color:#fdcb6e"><i class="fa fa-edit" ></i>UBAH</a> <a href="{{URL::to('/cetakpdf')}}/{{$dt->id}}" class="btn btn-xs btn-default" target="_blank">PDF</a></td>
    </tr>


    @endif


    @endforeach
  
  
    
  </tbody>
</table>



                </div>
            </div>
        </div>
    </div>
</div>


@endsection
@section('js')

<script type="text/javascript">
  $(document).ready( function () {
    $("#example").DataTable();
    // tutup / close modal nomor
    $('.tutup').click(function(e){
      location.reload();
    });
    // end modal nomor

    $.ajaxSetup({
    headers: {
        'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
    }
    });
    // $('#example').DataTable();

    $('#berinomor').click(function(e){
      var idsurat = $("input[name=idsurat]").val();
      alert(idsurat);
      // $('#myModal').modal({backdrop: 'static', keyboard: false}) 
      // $('#myModal').modal('show');
     
      // panggil modal dialog
    })
    // alert("test");
      // $('#myTable').DataTable();
      // var a =  $('#myTable').DataTable();
      // console.log(a)
      // alert("test");

      $('#berinommor').click(function(e){
        e.preventDefault();
        $('#info').html('');
        var info;
        // alert("test")  
          $.ajax({
          type: "POST",
          url: "{{URL::to('/berinomor')}}",
          data:  $('#formnomor').serialize(), 
          success: function( data ) {
              console.log(data)
              if(data.status_code == 1){
                // info = '<p> NOMOR SUDAH DIPAKAI !!</p>';
                info = '<div class="alert alert-danger" role="alert"> NOMOR SUDAH DIPAKAI !!</div>'; 
              }else{
                info = '<div class="alert alert-success" role="alert">PEMBERIAN NOMOR SUKSES </div>';
              }
              $('#info').append(info);
            }
          });
      });

      function reload(){
        location.reload();
      }
  } );

  function idSurat(id){
    $('idsurat').html('')
    var html = '<input type="hidden" name="idsurat" value="'+id+'"/>';
    $('#idsurat').append(html);
    $('#myModal').modal({backdrop: 'static', keyboard: false}) 
  }


  
  </script>

  
  


@endsection